### ISSUE TITLE
关于基地的宣传品牌的名称

### ISSUE THREAD

**Issue by will-ww** [ECNU/OpenDL#1]
可以在本 issue 下提出相关而有趣的基地名称，后续同步在包括公众号、B 站、小红书、Youtube 等媒体平台上进行宣传~

先抛出几个砖：

- 嘉数汇（原个人公众号，当时做大数据的通识教育用的）
- 数尔摩斯（将“数”这个关键词和一些流行上口的词汇进行组合）
- 百技乐典（类似的丛谈、观止、博物等的结合）
- 终身数字素养（和国家的一些口号对应）
- 大写的D（Digital）
- 七巧板/图（和我们数字素养框架七大领域对应，寓教于乐的教具，中国元素，类似的还有七艺，可以组合，如七巧新艺）

再给一些参考文章：
- 数字素养重要性是什么：https://www.zhihu.com/question/349399677/answer/1362062406
- 国际数字素养研究演进、热点与启示：https://www.sohu.com/a/522669847_670057
- 面向老年人的数字素养课程：https://le.ouchn.cn/educationCourseDetails/1dbcf2c4-c90f-bace-b75f-32ac8d5a4ef2

**Comment by will-ww** [comment]
再例如，以七巧板为例，可以演绎出如下名称：
- 七巧图/智慧板/燕几图/蝶翅几/唐图：[Wiki](https://en.wikipedia.org/wiki/Tangram)
- 图灵的七巧板（七巧图灵）：加入计算机要素
- 七巧（数字）世界
- 七巧新艺（七巧七艺）：七巧板 + 七艺（希腊通识）
- 七巧新谱：最早记录七巧板的[书籍](https://www.zhihu.com/topic/19742353/intro)
- 七巧花狮：花狮是华师的谐音
- 七巧教育科技：公司名称

其他类似的词还有：魔方、积木、九连环、华容道等 :-)

**Comment by AliceCodeZhang** [comment]
光是七巧，感觉和数字素养很难挂钩哎 
图灵七巧
数字未来
数字七巧
数字加速器
数字原住民加速站
数字未来加油站

**Comment by veronipp** [comment]
数字魔方
数字图灵
数字人生
数字掌门人Digitsman
数智图灵
未来数字人
数智达人
数字巧行者

**Comment by will-ww** [comment]
- 知数达理

**Comment by AliceCodeZhang** [comment]
一介数生

**Comment by AliceCodeZhang** [comment]
未来数字人

**Comment by will-ww** [comment]
> 数字未来加油站

Running Digital Future
